# Generated by Django 2.1.7 on 2019-03-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20190315_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='p_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
